Add support for PSR-18 HTTP clients
simplepie/simplepie pull request #777
Opened 2023-01-27 14:32 UTC by Art4

Hi all 👋 

This is a follow up of #774 and will add support for every PSR-18 HTTP client implementation.

This PR will fixes #520. I propose this PR for SimplePie 1.9.0, see #731.

2023-02-16 14:51 UTC, Art4 commented on src/Content/Type/Sniffer.php
> +    public function __construct(/* File */ $file)
Removing the type hint is no breaking change because we have not released 1.9.0

2023-02-17 11:45 UTC, Art4 commented
This PR is ready for review. Because this PR is build on #774 I recommend to merge this PR first. If will fix some BC breaks that comes with #774.

To show only the changes between #774 and #777 you can look at the diff between the branches: https://github.com/Art4/simplepie/compare/split-file-into-client-and-response...Art4:simplepie:add-psr18-http-client-support

2023-06-12 22:49 UTC, jtojnar requested changes
Still need to resolve the question of [non-absolute Location header](https://github.com/simplepie/simplepie/pull/826#discussion_r1142088339) and [Redirect tracking](https://github.com/simplepie/simplepie/pull/826#discussion_r1227293061).

2023-06-12 22:49 UTC, jtojnar commented on src/HTTP/Psr18Client.php
> +                    $permanentUrl = $requestedUrl;
We need some kind of mechanism to not change the permanent URL after temporary redirects (as tested by https://github.com/simplepie/simplepie/pull/819). For example, this is what File does:

https://github.com/simplepie/simplepie/blob/e356f5dc711ad4c5d92091a7dea509bf7c1c11a6/src/File.php#L144-L144

2023-08-25 08:22 UTC, mblaney commented
thanks @Art4 this looks good, can we merge and handle the redirect case separately?

2023-08-25 10:49 UTC, Art4 commented
@mblaney I resolved all conflicts and fixed all PHPStan errors.

2023-08-26 08:55 UTC, merged