SimplePie: Prepare PubSubHubbub for PSR-18 clients
simplepie/simplepie pull request #838
Opened 2023-05-31 01:45 UTC by jtojnar

Previously, this only supported `File`, let’s prepare for other `Response` implementations.

Also fixes a bug where it would clear previous links (by setting it to comma instead of appending).
And where it would add redundant `rel=self` link.

2023-05-31 01:49 UTC, jtojnar commented on src/HTTP/Response.php
> +    /**
Again, not sure if we should duplicate the comments, rather than using `{@inheritdoc}`

2023-09-13 08:57 UTC, Art4 approved these changes

2024-01-10 10:20 UTC, Art4 commented
@mblaney Are there any objections?

2024-01-10 10:21 UTC, jtojnar commented
I will try to get back to SimplePie development on weekend.

2024-01-13 04:00 UTC, mblaney commented
> @mblaney Are there any objections?

no this looks good to me :+1:

2025-06-26 12:26 UTC, Art4 commented
We should add some tests.

2025-06-27 06:04 UTC, jtojnar commented on src/HTTP/Response.php
> +    /**
Turns out it is fully redundant, removing it in #920

2025-06-27 07:06 UTC, jtojnar commented
Doing some more research, I am still not completely sure what the point is.

It was introduced in 01eb2c543b7fefb27ae67df65e2d19345ffaf808 and refactored in 426dc5b33fca1405bba47f387794ccf1a6b00b00.

The only idea for why we could have been promoting links to heasers is to allow `a[rel="hub"]` to be found by `SimplePie::get_link()` (since `link` elements should be picked up automatically).

But [searching GitHub](https://github.com/search?utf8=%E2%9C%93&q=%2F%3Ca+rel%3D%28%22hub%22%7Chub%7C%27hub%27%29%2F&type=code), I only found one relevant reference: a [chat log](https://chat.indieweb.org/dev/2016-11-21#t1479767303222000) of a discussion, whose conclusion was that [clients MUST NOT support `a[rel="hub"]`](https://github.com/w3c/websub/issues/67).

So perhaps this should be excised?

2025-06-29 13:33 UTC, jtojnar commented
Turns out `SimplePie::get_links()` does not consider `link` elements from HTML files so the `store_links()` method is still needed even if we do not want to support `a[rel]`.

Added tests, split the fixes into separate commits, and changed `get_headers` to return array of non-empty-array of string.

2025-06-29 14:43 UTC, jtojnar commented
Also removing support for `a[rel]`.

2025-06-30 08:12 UTC, Art4 requested changes

2025-06-30 08:12 UTC, Art4 commented on src/SimplePie.php
>                              $self = $locate->get_rel_link('self');
Isn't this a problem too? The RFC first moved links with `rel=hub` into the `<head>` section and later into the headers. They are still supported as links in the `<head>` for historical reasons but in favor of headers.

From https://w3c.github.io/websub/#h-note-0

> When perfoming discovery, subscribers MUST implement all three discovery mechanisms in the following order, stopping at the first match:
> 
> - Issue a GET or HEAD request to retrieve the topic URL. Subscribers MUST check for HTTP Link headers first.
> - In the absence of HTTP Link headers, and if the topic is an XML based feed or an HTML page, subscribers MUST check for embedded link elements.
> 

But `Locator::get_rel_link('hub')` will search in the complete body, not only in the `<head>` section. Can we make sure `Locator` looks only into the `<head>` section for efficiency? And can we add a test that shows that `rel=hub` from headers will not be overwritten by a `rel=hub` from `<head>` section (and more important) not overwritten by a `rel=hub` from `<body>` section?

2025-06-30 08:12 UTC, Art4 commented on tests/Integration/SimplePieTest.php
> +            'selfUrl' => 'https://example.com/',
`rel=hub` only from `<body>` section should not be supported.

```suggestion
            'hubUrl' => null,
            'selfUrl' => null',
```

2025-06-30 08:12 UTC, Art4 commented on tests/Unit/ParserTest.php
> +            file_get_contents(dirname(__FILE__, 2) . '/data/microformats/h-feed-simple.html'),
Can we keep the heredoc for better readability and just indent it properly?

```suggestion
            <<<HTML
            <!-- SPDX-FileCopyrightText: 2018 Aaron Parecki -->
            <!-- SPDX-License-Identifier: CC0-1.0 -->
            <!-- SPDX-ArtifactOfProjectName: php-mf2 -->
            <html>
                <head>
                    <title>Test</title>
                </head>
                <body>
                    <div class="h-feed">
                        <a href="/author" class="p-author h-card">Author Name</a>
                        <ul>
                            <li class="h-entry">
                                <a href="/1" class="u-url p-name">One</a>
                            </li>
                            <li class="h-entry">
                                <a href="/2" class="u-url p-name">Two</a>
                            </li>
                            <li class="h-entry">
                                <a href="/3" class="u-url p-name">Three</a>
                            </li>
                            <li class="h-entry">
                                <a href="/4" class="u-url p-name">Four</a>
                            </li>
                        </ul>
                    </div>
                </body>
            </html>
            HTML
            ,
```

2025-06-30 19:35 UTC, jtojnar commented on src/SimplePie.php
>                              $self = $locate->get_rel_link('self');
As described in <https://www.w3.org/TR/websub/#x8-1-discovery>:

> The decision about whether a subscriber should look for `<link>` elements inside a page's `<body>` (as well as the `<head>`) is not straightforward, and there is currently no clear consensus.

2025-06-30 19:35 UTC, jtojnar commented on tests/Unit/ParserTest.php
> +            file_get_contents(dirname(__FILE__, 2) . '/data/microformats/h-feed-simple.html'),
I would love to use https://cs.symfony.com/doc/rules/whitespace/heredoc_indentation.html but it requires PHP 7.3: https://wiki.php.net/rfc/flexible_heredoc_nowdoc_indentation

2025-06-30 20:37 UTC, jtojnar commented on tests/Integration/SimplePieTest.php
> +            'selfUrl' => 'https://example.com/',
Same as above. We could modify the xpath expression but `link` element is probably less likely to slip through injection filrers than `a[rel]` so I understand the lack of consensus.

2025-06-30 20:38 UTC, jtojnar commented on src/SimplePie.php
>                              $self = $locate->get_rel_link('self');
Made the handling of both rels symmetric: [`9ad8817` (#838)](https://github.com/simplepie/simplepie/pull/838/commits/9ad88175380d38635bbf29abb55412643c88b1ac)

2025-07-01 11:41 UTC, Art4 commented on tests/Integration/SimplePieTest.php
> +            'selfUrl' => 'https://example.com/',
Difficult topic.. Can we at least make sure that the following example results into `example.com` instead of `evil.example.com`?

```<html>
    <head>
        <title>Test</title>
        <link rel="hub" href="https://pubsubhubbub.appspot.com">
        <link rel="self" href="https://example.com">
    </head>
    <body>
        <link rel="hub" href="https://pubsubhubbub.appspot.com">
        <link rel="self" href="https://evil.example.com">
        <div class="h-feed">
        </div>
    </body>
</html>```

2025-07-01 20:40 UTC, jtojnar commented on tests/Integration/SimplePieTest.php
> +            'selfUrl' => 'https://example.com/',
That would be handled by the first link taking precedence. But I had a change of mind and decided to just drop the non-head support.

2025-07-01 21:36 UTC, jtojnar commented
This now also appears to be blocked by #921

2025-07-29 17:56 UTC, Art4 approved these changes
Thanks for the great work. 👍

2025-07-29 21:38 UTC, merged